# Generated by Django 4.2.30 on 2026-08-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('contact_no', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SecureFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(db_index=True, max_length=50)),
                ('filename', models.CharField(max_length=200)),
                ('ephemeral_pub', models.CharField(max_length=128)),
                ('salt', models.CharField(max_length=64)),
                ('nonce', models.CharField(max_length=64)),
                ('hashcode', models.CharField(max_length=128)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('owner', 'filename')},
            },
        ),
    ]
